---
title: "Lab 14 - Bivariate Regression & Interpretation"
author: "Jackson Nahpi"
date: "November 28, 2017"
output:
  pdf_document: default
---

Complete the following exercises below and include all code used to find the answers. Knit together the PDF document and commit both the Lab 14 RMD file and the PDF document to Git. Push the changes to GitHub so both documents are visible in your public GitHub repository.

**1. Select the main focal relationship you're interested in exploring for your poster project.**

  a. Describe the response variable and the explanatory variable and the theoretical relationship you believe exists between these two variables. 
  

The response variable I want to use is the respondents percieved probability of finishing college and my explanatory variable will be the level of rewards they recieved due to their grades. I believe that there may be a positive relationship between the two variables since rewards for grades may influence a respondents work ethic and therefore may feel more inclined to try harder in college due to knowing their may be a payout to doing so.
  
  
  b. Conduct a simple (bivariate) linear regression on your focal relationship and save the model object. Print out the full results by calling `summary()` on your model object. 
  
  
```{r, echo = FALSE, working= FALSE}
model_0 <- lm(probfincol ~ pnshdeviancelyr, data = freshman_dataset_v4)
summary(model_0)
```
  
  
  c. What is the direction, magnitude, and statistical significance of the bivariate association between the explanatory and response variables. 
  
  
The direction of the relationship is positive, however the magnitude and significance of the bivariate association are both weak. The magnitude is only about 0.01 and the probability that it is due to chance is a p-value of 0.334.
  
  
  d. What is the meaning of the model intercept?
  
  
The intercept represents the expected value of y when x is equal to zero. Therefore, when x is zero in this model the expected value of y is 9.75.

  
  e. How well does the bivariate model fit the data? How is this information calculated?
  
  
The bivariate model in this situation does not fit the data well at all. The R-squared value  0.0002563 which essentially shows how poor of a fit this model is since it is near 0. The information about fit is calculated through the R-squared this is enough to where we don't even need to look at the adjusted R-squared to confirm how poor the fit is.
  
  
  f. Is the observed association between the independent variable and dependent variable consistent with your hypothesis? Why or why not?
  
  
No it is not, I believed there would be a relationship between the two variables and instead the result shows no relationship among the two variables. We cannot reject the null hypothesis of the two variables not being related to one another.
  
  
**2. Select a different focal relationship related to your project. This could be:**

* **A different response and a different explanatory variable**

* **A different response and the same explanatory variable**

* **The same response and a different explanatory variable**

  a. Describe the response variable and the explanatory variable and the theoretical relationship you believe exists between these two variables. 
  
  b. Conduct a simple (bivariate) linear regression on your focal relationship and save the model object. Print out the full results by calling `summary()` on your model object. 
  c. What is the direction, magnitude, and statistical significance of the bivariate association between the explanatory and response variables. 
  
  d. What is the meaning of the model intercept?
  
  e. How well does the bivariate model fit the data? How is this information calculated?
  
  f. Is the observed association between the independent variable and dependent variable consistent with your hypothesis? Why or why not?
